<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="MasterPage1.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h1 class="" style="box-sizing: border-box; margin: 20px 0px 10px; font-size: 36px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Nagpur University Syllabus -<span>&nbsp;</span><i style="box-sizing: border-box;">Nagpur University Syllabus Classes Training Course</i></h1>
<div class="divider" style="box-sizing: border-box; width: 886.662px; margin: 20px auto 15px; position: relative; height: 1px; backface-visibility: hidden; transform: translateZ(0px) scale(1, 1); color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</div>
<p style="box-sizing: border-box; margin: 0px 0px 30px; font-size: 16px; color: rgb(102, 102, 102); line-height: 1.4; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</p>
<p style="box-sizing: border-box; margin: 0px 0px 30px; font-size: 16px; color: rgb(102, 102, 102); line-height: 1.4; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</p>
<p style="box-sizing: border-box; margin: 0px 0px 30px; font-size: 16px; color: rgb(102, 102, 102); line-height: 1.4; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</p>
<div class="col-md-6" style="box-sizing: border-box; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 443.325px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/bca-syllabus-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="BCA ">BCA</a><span>&nbsp;</span>Bachelor Of Computer Application,</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/bcca-syllabus-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="BCCA ">BCCA</a>&nbsp;Bachelor of Commerce &amp; Computer Application&nbsp;</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/BE-IT-CS-syllabus-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="BE (IT/CS)">BE<span>&nbsp;</span></a>&nbsp;Information technology / Computer Science&nbsp;/ Civil</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/b-arch-syllabus-nagpur-university.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="B.Arch ">B Arch</a><span>&nbsp;</span>Bachelor Of Architecture,</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/mca-syllabus-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="MCA">MCA</a>&nbsp;Master of Computer Application</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/mcm-syllabus-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="MCM">MCM</a>&nbsp;&nbsp;Master of Computer Management</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/bsc-syllabus-nagpur-university.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="B.Sc">BSc</a><span>&nbsp;</span>Bachelor of Science</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/bcom-syllabus-rtmnu-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="B.Com ">B.Com</a><span>&nbsp;</span>Bachelor Of Commerce,</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/diploma-syllabus-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="Diploma">Diploma</a>&nbsp; Polytechnic</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/other-computer-syllabus-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="Others">Others</a>&nbsp;Other Degree Courses</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/rtmnu-syllabus.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="RTMNU Syllabus">RTMNU Syllabus</a><span>&nbsp;</span>RTM Nagpur University</h2>
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;">Basic Programming</h2>
    <a href="https://www.atlantacomputer.in/c-classes-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="C ">C / C++<span>&nbsp;</span></a>,&nbsp;<a href="https://www.atlantacomputer.in/java-courses-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="Java">Java</a><h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;">Testing</h2>
    <a href="https://www.atlantacomputer.in/software-testing-courses-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="Software Testing">Software Testing</a>,<h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;">Hardware &amp; Networking</h2>
    <a href="https://www.atlantacomputer.in/ccna-course-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="CCNA ">CCNA</a>,<span>&nbsp;</span><a href="https://www.atlantacomputer.in/mcse-course-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="MCSE ">MCSE</a>,<span>&nbsp;</span><a href="https://www.atlantacomputer.in/computer-hardware-coaching-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="Computer Hardware">Hardware</a>,<span>&nbsp;</span><a href="https://www.atlantacomputer.in/computer-networking-coaching-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="Computer Networking ">Networking<span>&nbsp;</span></a>,<a href="https://www.atlantacomputer.in/ccnp-course-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="CCNP">CCNP</a>,&nbsp;<a href="https://www.atlantacomputer.in/cisco-ccie-training-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="CCIE">CCIE</a><br style="box-sizing: border-box;" />
    <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;">Animation</h2>
    <div style="box-sizing: border-box;">
        <a href="https://www.atlantacomputer.in/design-and-animation.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="Design and Animation Classes">Design and Animation</a>,&nbsp;<a href="https://www.atlantacomputer.in/animation-courses-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="Advance Animation Courses">Advance Animation Diploma</a></div>
    <div style="box-sizing: border-box;">
        <h2 style="box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; color: inherit; margin-top: 20px; margin-bottom: 10px; font-size: 30px;"><a href="https://www.atlantacomputer.in/foreign-language-classes-nagpur.html" style="box-sizing: border-box; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none;" title="Foreign Languages">Foreign Languages</a>&nbsp;&nbsp;Foreign Languages</h2>
    </div>
</div>
</asp:Content>
